### ISSUE TITLE
get_hash() fails on big-endian architectures

### ISSUE THREAD

**Issue by umlaeute** [rbdannenberg/o2#23]
running `./arraytest` on a BIGendian machine (like s390x) aborts with an assertion:

```sh
$ ./arraytest 
arraytest: .../o2/src/o2node.cpp:239: int64_t get_hash(O2string): Assertion `((c & 0xff) && (c & 0xff00) && (c & 0xff0000) && (c & 0xff000000)) || ((((c & 0xff) != 0) || ((c & 0xff00) == 0)) && (((c & 0xff00) != 0) || ((c & 0xff0000) == 0)) && ((c & 0xff000000) == 0))' failed.
Aborted
```

this is because the assertion uses bitmasks that are only valid for littleendian.
here's a patch for o2-1.1:
https://salsa.debian.org/multimedia-team/o2/-/blob/master/debian/patches/big_endian.patch

eventually i will update the patch for o2-2.x and submit a PR (if you want to)

**Comment by umlaeute** [comment]
also note that there's no `-mcx16` flag on s390x (which is a 64bit BIGendian architecture), so for now i have just removed this compiler flag (without thinking about consequences so far...)

**Comment by rbdannenberg** [comment]
Yes. I thought I was going to test on an Apple M2, but now realize M2 is also littleendian. I followed the patch, but found a simpler boolean expression for the assert and will push changes after more testing. Thanks.
