### ISSUE TITLE
configure succeeds if libavahi-client-dev is not present

### ISSUE THREAD

**Issue by umlaeute** [rbdannenberg/o2#25]
running `cmake` without having the libavahi-client development headers installed succeeds without error, but the build fails.
you probably should check for their presence in the configuration stage and abort early.

**Comment by rbdannenberg** [comment]
I'd be happy to include a patch for checking, but I'm not sure how to do it robustly. The top-level README.md already says "you need the `avahi-client-dev` package to be installed."
