### ISSUE TITLE
arraytest fails on i386

### ISSUE THREAD

**Issue by umlaeute** [rbdannenberg/o2#26]
o2-1.1 also fails on `i386` (aka `x86`, `x86_32` or just "Intel 32bit"), but that seems to be "only" an issue in the actual tests: comparing floats for equality with `123.456F+i` is a brittle thing, esp. when coercing values.

A patch for the bad comparison could be found at https://salsa.debian.org/multimedia-team/o2/-/blob/master/debian/patches/float_comparision.patch

The patch is against o2-1.1 (so it won't apply against o2-2.x), but I'm currently stuck with #24 so with o2-2.x I don't even get to the float-comparision in my test-runs.
However, looking at https://github.com/rbdannenberg/o2/blob/253d109f4a2eaf62a885663ca50a34a6f04dbd74/test/arraytest.cpp#L502 gives me no reason to believe that the underlying issue has gone away...

**Comment by rbdannenberg** [comment]
Thanks. I think this is fixed now (will be pushed soon). The patch seems to be gone now, so I'm doing arg-v.vf[i] == (float) (123.456F + i). Float compares are tricky, but in this case we're creating compared bits with exactly the same expression: (123.456F + i) coerced or stored to float32.

**Comment by umlaeute** [comment]
sorry for the wrong link to the patch. it should have been 
https://salsa.debian.org/multimedia-team/o2/-/blob/master/debian/patches/float_comparison.patch

(i've fixed the typo in the patch filename, which obviously broke the link)

**Comment by rbdannenberg** [comment]
Thanks. I think the patch is way overkill since the test has nothing to do with floating point approximation and only has to do with sending a bit pattern and checking that the same bits arrive.  Yes, I missed one (float) coercion, but it's fixed now. Or if not, I'd rather find out than hide the problem with and approximate equals test.

**Comment by umlaeute** [comment]
e83488f166bb5d58ba672217dd0c2a3cf3031874
